### ISSUE TITLE
About pretrained vit backbone

### ISSUE THREAD

**Issue by LvRenbaba** [zuwenqiang/EPT#1]
thanks for your great work! 
you mentioned in paper the pretrained vit model you used is vit-large, but i read the code in configs/vit-b16_ept/colon_1shot.py, it seems the model in code is a vit-base, is something wrong with the code?

**Comment by zuwenqiang** [comment]
Thank you for your interest in our research.

We conducted the experiments with both vit-base and vit-large, with vit-base being the default as indicated in the paper. Specifically, Table 1 presents the results for vit-base, while Table 2 shows the results for vit-large.

**Comment by LvRenbaba** [comment]
> Thank you for your interest in our research.
> 
> We conducted the experiments with both vit-base and vit-large, with vit-base being the default as indicated in the paper. Specifically, Table 1 presents the results for vit-base, while Table 2 shows the results for vit-large.

Sorry i didn't read the paper carefully, thanks for your reply!
